name: 'sftp-upload'
description: 'Every one to the SFTP!'
inputs:
  host:
    description: 'Server to connet to'
    required: true
  username:
    description: 'Username when connecting'
    required: true
  password:
    description: 'Password'
    required: true
  paths:
    description: 'key value pair of file local and file remove'
    required: true 
  port:
    description: 'Port if other than default'
    required: false 
    default: 22
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
